package nz.ac.aut.ense701.gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import nz.ac.aut.ense701.gameModel.Game;
import nz.ac.aut.ense701.gameModel.Terrain;

/*
 * Panel for representing a single GridSquare of the island on the GUI.
 * 
 * @author AS
 * @version 1.0 - created
 */

public class GridSquarePanel extends javax.swing.JPanel 
{
    private Image backgroundImage;
    
//    @Override
//    protected void paintComponent(Graphics g) {
//        super.paintComponent(g);
//        g.drawImage(bgImage, 0, 0, null);
//    }
    /** 
     * Creates new GridSquarePanel.
     * @param game the game to represent
     * @param row the row to represent
     * @param column the column to represent
     */
    public GridSquarePanel(Game game, int row, int column)
    {
        this.game   = game;
        this.row    = row;
        this.column = column;
        initComponents();
    }

    /**
     * Updates the representation of the grid square panel.
     */
    public void update()
    {
        // get the GridSquare object from the world
        Terrain terrain   = game.getTerrain(row, column);
        boolean squareVisible = game.isVisible(row, column);
        boolean squareExplored = game.isExplored(row, column);
        
        Color      color;
        
        switch ( terrain )
        {
            case SAND     : color = Color.YELLOW; break;
            case FOREST   : color = Color.GREEN;  break;
            case WETLAND : color = Color.BLUE; break;
            case SCRUB : color = Color.DARK_GRAY;   break;
            case WATER    : color = Color.CYAN;   break;
            default  : color = Color.LIGHT_GRAY; break;
        }
        
        if ( squareExplored || squareVisible )
        {
            String occupantSymbol = game.getOccupantStringRepresentation(row, column);
            // Set the text of the JLabel according to the occupant
            lblText.setText(occupantSymbol);
            // Set the colour. 
            if ( squareVisible && !squareExplored ) 
            {
                // When explored the colour is brighter
                color = new Color(Math.min(255, color.getRed()   + 128), 
                                  Math.min(255, color.getGreen() + 128), 
                                  Math.min(255, color.getBlue()  + 128));
            }
            lblText.setBackground(color);


            if(game.hasPlayer(row,column)) {
                setBackground();
            } else {
                clearBackground();
                setBorder(normalBorder);
            }
            
            //switch statements can't be used on strings in this version of JDK
            //so IF statements.
            if(occupantSymbol.contains("K")){lblText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/kiwi.png")));}
            if(occupantSymbol.contains("F") || occupantSymbol.contains("P")){lblText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/animal.png")));}
            if(occupantSymbol.contains("H")){lblText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/hole.png")));}
            if(occupantSymbol.contains("T")){lblText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/trap.png")));}
            if(occupantSymbol.contains("E")){lblText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/food.png")));}
      
            setBorder(game.hasPlayer(row,column) ? activeBorder : normalBorder);
        }
        else
        {
            lblText.setText("");
            lblText.setBackground(null);
            setBorder(normalBorder);
        }
    }
    
    
    public void clearBackground() {
        setImage("empty.png");
    }
    public void setBackground() {
        setImage(game.getGameCharacter());     
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        g.drawImage(backgroundImage,0,0,null);
    }
    public void setImage(String fileName) {
        String workingDirectory = System.getProperty("user.dir");
        String basePath = (workingDirectory + File.separator + "src" + File.separator + "images" + File.separator + "icon" + File.separator);
        try {
            backgroundImage = ImageIO.read(new File(basePath + fileName));
        } catch(Exception ex) {
            System.out.println("Couldn't find file");
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new java.awt.BorderLayout());

        lblText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblText.setOpaque(true);
        add(lblText, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables
    
    private Game game;
    private int row, column;
    
    private static final Border normalBorder = new LineBorder(Color.BLACK, 1);
    private static final Border activeBorder = new LineBorder(Color.RED, 3);
}
